query ($num_repos: Int!, $cursor: String!) {
  search(query: "language:Java, stars:>1, sort:stars-desc", type: REPOSITORY, first: $num_repos, after: $cursor) {
    edges {
      node {
        ... on Repository {
          name
          stargazerCount
          url
          sshUrl
          createdAt
          updatedAt
          releases {
            totalCount
          }
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
    }
  }
}