{
  search(query: "language:Java, stars:>1, sort:stars-desc", type: REPOSITORY, first: 10) {
    edges {
      node {
        ... on Repository {
          name
          url
          sshUrl
          createdAt
          stargazerCount
          releases {
            totalCount
          }         
        }
      }
    }
  }
}