query($num_repos: Int!) {
  search(query: "language:Java, stars:>1", type: REPOSITORY, first: $num_repos) {
    edges {
      node {
        ... on Repository {
          name
          url
          sshUrl
          createdAt
          stargazerCount
          releases {
            totalCount
          }
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}